;;; auctex-latexmk-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from auctex-latexmk.el

(autoload 'auctex-latexmk-setup "auctex-latexmk" "\
Add LatexMk command to TeX-command-list.")

;;; End of scraped data

(provide 'auctex-latexmk-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; auctex-latexmk-autoloads.el ends here
